# DB への接続情報
jdbcSettings:
  url: "jdbc:h2:tcp://localhost/~/sample"
  username: "sa"
  password: "sa"
  driverClassName: "org.h2.Driver"

# 生成したコードを置く package を指定
packageName: "com.example.entity"

# java等のインストールドライブとprojectのドライブが異なるため、entity生成先をフルパスで指定（変数化したい）
outputDirectory: "D:/programing/github/sample/src/main/java"

interfaceRules:
  # If you just specify the interfaces, all the generated classes'll implement the interfaces.
- interfaces: [{name: "java.io.Serializable"}]

# TblCity entityにTblCountryを付与する
additionalCodeRules:
  - className: "TblCity"
    # position: "Bottom"
    code: |
            @ManyToOne
            @JoinColumn(name = "`country_code`", insertable = false, updatable = false)
            private TblCountry tblCountry;